const movies = [
  {
    _id: "5b31abceab1",
    title: "Terminator",
    genere: { _id: "5b21cbea212", name: "Action" },
    numberInStock: 5,
    dailyRentalRate: 2.5,
    publishDate: "2018-01-02",
    liked: true,
  },
  {
    _id: "5b31abceab2",
    title: "Infinity War",
    genere: { _id: "5b21cbea29", name: "Drama" },
    numberInStock: 5,
    dailyRentalRate: 2.5,
    publishDate: "2018-01-02",
    liked: false,
  },
  {
    _id: "5b31abceab11",
    title: "End Game",
    genere: { _id: "5b21cbea28", name: "Action" },
    numberInStock: 5,
    dailyRentalRate: 2.5,
    publishDate: "2018-01-02",
    liked: false,
  },
  {
    _id: "5b31abceab12",
    title: "50 Shade Shadow",
    genere: { _id: "5b21cbea27", name: "Action" },
    numberInStock: 5,
    dailyRentalRate: 2.5,
    publishDate: "2018-01-02",
    liked: false,
  },
  {
    _id: "5b31abceab13",
    title: "Mulan",
    genere: { _id: "5b21cbea26", name: "Action" },
    numberInStock: 5,
    dailyRentalRate: 2.5,
    publishDate: "2018-01-02",
    liked: false,
  },
  {
    _id: "5b31abceab14",
    title: "Once upon in time in china",
    genere: { _id: "5b21cbea25", name: "Action" },
    numberInStock: 5,
    dailyRentalRate: 2.5,
    publishDate: "2018-01-02",
    liked: false,
  },
  {
    _id: "5b31abceab15",
    title: "Dota",
    genere: { _id: "5b21cbea24", name: "Action" },
    numberInStock: 5,
    dailyRentalRate: 2.5,
    publishDate: "2018-01-02",
    liked: false,
  },
  {
    _id: "5b31abceab16",
    title: "Mobile Legends",
    genere: { _id: "5b21cbea23", name: "Action" },
    numberInStock: 5,
    dailyRentalRate: 2.5,
    publishDate: "2018-01-02",
    liked: false,
  },
  {
    _id: "5b31abceab17",
    title: "Police story",
    genere: { _id: "5b21cbea22", name: "Action" },
    numberInStock: 5,
    dailyRentalRate: 2.5,
    publishDate: "2018-01-02",
    liked: false,
  },
  {
    _id: "5b31abceab18",
    title: "Domino",
    genere: { _id: "5b21cbea21", name: "Action" },
    numberInStock: 5,
    dailyRentalRate: 2.5,
    publishDate: "2018-01-02",
    liked: false,
  },
  {
    _id: "5b31abceab19",
    title: "B Lu",
    genere: { _id: "5b21cbea20", name: "Action" },
    numberInStock: 5,
    dailyRentalRate: 2.5,
    publishDate: "2018-01-02",
    liked: false,
  },
];

export const getMovies = () => movies;

export const getMovie = (id) => movies.find((mov) => mov._id === id);
